type Earning {
  _id: ID!
  year: Int!
  month: Int!
  amount: Float!
}

type SumEarning {
  sumCurrentYear: Float!
  sumOldYear: Float!
}

input EarningInput {
  year: Int!
  month: Int!
  amount: Float!
}

type Query {
  getEarningByWallet(walletID: ID!, year: Int!): [Earning!]!
  getSumEarning(walletID: ID!, year: Int!): SumEarning!
}

type Mutation {
  updateEarning(_id: ID, walletID: ID!, input: EarningInput!): Earning
}
