type Ticket {
  _id: ID!
  symbol: String!
  quantity: Float!
  averagePrice: Float!
  grade: Int!
}

input TicketInput {
  walletID: ID!
  symbol: String!
  quantity: Float!
  averagePrice: Float!
  grade: Int!
}

type Query {
  tickets: [Ticket!]
  getTicketsByWallet: [Ticket]
}

type Mutation {
  createTicket(input: TicketInput!): Ticket!
  updateTicket(_id: ID!, input: TicketInput!): Ticket
  deleteTicket(_id: ID!, walletID: ID!): Boolean!
}
