enum Status {
  BUY
  KEEP
  ANALYZE
}

type Rebalance {
  _id: ID!
  symbol: String!
  longName: String!
  status: Status!
  currentAmount: Float!
  gradePercent: Float!
  currentPercent: Float!
  targetPercent: Float!
  targetAmount: Float!
  financialCurrency: String!
}

type Query {
  rebalances(walletID: ID!): [Rebalance]
}
